# -*- coding: utf-8 -*-
"""AdsOptmizationReinforcement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1La-F-hty_7kEcBK4u2AHPkecXRcjzBG3
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount("content/gdrive")

# rename path
!ln -s /content/gdrive/My\ Drive/ /mydrive
#!ls

import pandas as pd
import matplotlib.pyplot as plt

path = "/mydrive/Data_Science_Projects/Ads_Optmization_Reinforcement/data/"
df = pd.read_csv(path + "Ads_Optimization.csv")
print(df.shape)
print(df.info())
print(df.describe())

# upper confidence bound
import math

number_ads = 10
observations = 1000
numbers_selections = [0] * number_ads
sum_rewards = [0] * number_ads
total_reward = 0
selected_ads = []

for n in range(0, observations):
  ads = 0
  max_upper_bound = 0
  for i in range(0, number_ads):

    if numbers_selections[i] > 0:
      average = sum_rewards[i]/numbers_selections[i]
      delta = math.sqrt(3/2 * math.log(n + 1) / numbers_selections[i])
      upper_bound = average + delta
    else:
      upper_bound = 1e400
    if upper_bound > max_upper_bound:
      max_upper_bound = upper_bound
      ads = i

  selected_ads.append(ads)
  numbers_selections[ads]  = numbers_selections[ads] + 1
  reward = df.values[n, ads]
  sum_rewards[ads] = sum_rewards[ads] + reward
  total_reward = total_reward + reward

print("Rewards by ads: ", sum_rewards)
print("Rewards by UCB: ", total_reward)
print("Ads selected: ", selected_ads)

# visualize
plt.hist(selected_ads)
plt.title("Histogram Ads selected")
plt.xlabel("Ads")
plt.ylabel("Number of times")
plt.show()

